### ISSUE TITLE
Add keywords to spelling dictionary

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#1]
It would be nice if HTML keywords (such as TD and CELLSPACING) and Help Builder functions (such as TopicLink) didn't display a red squiggly line in the editor.

**Comment by RickStrahl** [comment]
Yeah, i know but not sure how to isolate tag names etc from other words. I can exclude certain things explicitly. The type checking is manually implemented in the JS code for the editor and goes word by word and I'm still tweaking the logic for this. It's much better than it used to be in fact, but there's still some work to do.

What's your use case? Are you looking at classic Help Builder style topics or HTML embedded in Markdown?

**Comment by DougHennig** [comment]
Right now classic style.

**Comment by RickStrahl** [comment]
Yeah class style will definitely show a lot more squigglies. I can probably just catch that at the word parsing end. I'll see what I can do.

**Comment by RickStrahl** [comment]
I've added a number of exceptions for the spell checker to ignore which should definitely help in HTML mode. You should see a lot fewer spelling exceptions related to 'non-text' in both classic Html Help Builder as well as Markdown.
