### ISSUE TITLE
Templates localization

### ISSUE THREAD

**Issue by zdenekkrejci** [RickStrahl/HelpBuilderReleases#101]
For each Help Builder project, we edit template files first. Mostly due to proper localization.
We edit all templates that are directly available in main menu "View" -> "Edit Topic Templates" (Index, _Layout, Tableofcontens) as well as Header and Topic files.

But we must edit the KEYWORDS.HTM and FRAMES.HTM files after each building of output.
We have to add proper "html lang=" property to both files, "meta charset=" into Frames file, translate the "This page uses frames" paragraph, "Contents" phrase and html "title" tag with added english word "Keyword".
Should You release template files for these two files?

**Comment by RickStrahl** [comment]
Frames is no longer used. All pages generate their own HTML layout. 

I've added a template for `keywords.wcs` although the default template no longer actually links the keywords page. You'd have to add it manually.
