### ISSUE TITLE
No themes available

### ISSUE THREAD

**Issue by kentraub** [RickStrahl/HelpBuilderReleases#103]
When I select Select Theme in 5.22.0 no options come up for themes.  Is there a different spot to change themes?  I want to use the msword theme that I've used previously.

**Comment by RickStrahl** [comment]
Go to **Tools | Options  | Update Templates** to get the latest templates and themes from the installation into your project.

If you had an older project it may not had have had any themes...

If you're using an older project to update **make sure to back up first** as conversion is one way and may not be 100% compatible.
