### ISSUE TITLE
WWHB throws an error when attempting to use Tools->Export HTML output to Zip file

### ISSUE THREAD

**Issue by rikaye** [RickStrahl/HelpBuilderReleases#106]
See below.

#### Error Message:
OLE IDispatch exception code 0 from wwDotNetBridge: Method 'Westwind.WebConnection.FileUtils.SaveFileDialog' not found...

#### Module: 
PROCEDURE WWDOTNETBRIDGE.INVOKESTATICMETHOD WWDOTNETBRIDGE.FXP

#### Line:
688

#### Call Stack:
1. c:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | C:\Program Files (x86)\West Wind Html Help Builder\wwhelpmain.prg (307) |

----
2. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.timer | c:\program files (x86)\west wind html help builder\wwhelp.vct (30) |
   thisform.DoEditOperation(lcName)
----
3. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | c:\program files (x86)\west wind html help builder\wwhelp.vct (240) |
   		lcZipFileName = SaveFileDialog(JUSTPATH(THIS.oHelp.cFileName) + "\" + LOWER(JUSTSTEM(THIS.oHelp.cFileName)) + 				"_HTML_"  +  CHRTRAN(DTOC(DATE()),"/\","-") + ".zip","zip",          		"Zip Files|*.zip",.F.)
----
4. wwutils.fxp | savefiledialog | C:\webconnection\fox\classes\wwutils.prg (2943) |

----
5. wwdotnetbridge.fxp | wwdotnetbridge.invokestaticmethod | C:\webconnection\fox\classes\wwdotnetbridge.prg (688) |

----
6. errors.fxp | ON...  | C:\Program Files (x86)\West Wind Html Help Builder\errors.prg (120) |

----

#### Window:
WWHELPFORM

**Comment by RickStrahl** [comment]
You remember what you were doing when this happended? I can’t duplicate it…

 

It sounds like the version of wwDotnetBridge.dll is not correct. Can you check the version?

 

 

+++ Rick ---

 

Rick Strahl

West Wind Technologies

---

Making Waves on the Web

 <https://weblog.west-wind.com/> https://weblog.west-wind.com

 <https://markdownmonster.west-wind.com> https://markdownmonster.west-wind.com

**Comment by rikaye** [comment]
What I mentioned in the description. Just clicked on that menu option.

What version is WWHB expecting?

**Comment by rikaye** [comment]
Looks like the one in the HB bin folder is 7.12

**Comment by RickStrahl** [comment]
Ok I was able to duplicate. Invalid parameter passed produces an unexpected misleading error. Will be fixed in the next release.

You can try do this from the Build Dialog now - Build then export to Zip from there. I believe that works and does the same thing.


+++ Rick ---
