### ISSUE TITLE
Capture image crashes

### ISSUE THREAD

**Issue by rikaye** [RickStrahl/HelpBuilderReleases#108]
#### Error Message:
Class definition SCREENCAPTURE is not found.

#### Module: 
PROCEDURE WWHELPFORM.DOEDITOPERATION C:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\WWHELP.VCT

#### Line:
713

#### Call Stack:
1. c:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | C:\Program Files (x86)\West Wind Html Help Builder\wwhelpmain.prg (307) |

----
2. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.otoolbar.click | c:\program files (x86)\west wind html help builder\wwhelp.vct (5) |
   THISFORM.tmrToolbar.SetTool(Tool)
----
3. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.settool | c:\program files (x86)\west wind html help builder\wwhelp.vct (29) |
   thisform.DoEditOperation(lcName)
----
4. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | c:\program files (x86)\west wind html help builder\wwhelp.vct (713) |
   		loCaptureForm = CREATEOBJECT("ScreenCapture",THISFORM,.T.)
----
5. errors.fxp | ON...  | C:\Program Files (x86)\West Wind Html Help Builder\errors.prg (120) |

----

#### Window:
WWHELPFORM

**Comment by RickStrahl** [comment]
Got any more info on this? 

I can't duplicate this.

**Comment by rikaye** [comment]
All I did was select the screen cap option from the Tools menu while I had my main help project open and it generated that error report. Today it's not generating an error but it's also not visibly doing anything. Does it spawn some process I could see in Task Manager?

**Comment by RickStrahl** [comment]
Yes - there's a `ScreenCapture.exe` that gets launched.

I wonder if this is related to the path issues we were reviewing with the version not updating. It seems like the path the app is running from is not in the startup folder somehow. If wwhelp.exe is not running out of the startup folder it's going to have problems finding related resources (or even wwhelp.exe for the version check).

Maybe check in Process Explorer - I think it shows you the active path for the running application.

**Comment by rikaye** [comment]
Here's what procexp shows me:

![image](https://user-images.githubusercontent.com/28717887/95111359-5f504f00-070d-11eb-8913-4975a9b3d397.png)

There's no evidence of the screencapture.exe process you mentioned running. But, I found that EXE in the WWHB bin sub-folder. And that bin folder is not in my path.

**Comment by RickStrahl** [comment]
ScreenCapture.exe is launched as needed when you invoke the screen capture. 

So maybe do this:

Next time when this fails, take a look at Process Explorer and see what the current directory is (PE shows that on the first page). The Bin folder shouldn't have to be in the path as help builder adds it, but it adds it as `.\bin` - so if the Help Builder folder changes somehow `.\bin` may no longer point at the right place.

Making a change to explicitly set the path during startup by using:

```foxpro
set path to (FULLPATH(".\bin")) ADDITIVE
```

which should ensure that the file can be found by FoxPro to launch.

**Comment by rikaye** [comment]
That was in the screenshot. It's running out of program files x(86) etc. Standard location as best I can tell. 

> C:\Program Files (x86)\West Wind Html Help Builder\wwhelp.exe

Are you recommending I add a WWHB startup prg as discussed in the docs?

**Comment by rikaye** [comment]
![image](https://user-images.githubusercontent.com/28717887/95136961-1b714000-0735-11eb-89ad-9fc804dece81.png)

**Comment by rikaye** [comment]
As I already have a screen capture tool I use I'm not all that concerned about this, Rick. It was more an FYI that it doesn't load on my system.
