### ISSUE TITLE
HelpBuilderConsole.exe BUILDPROJECT -p

### ISSUE THREAD

**Issue by kennetherland** [RickStrahl/HelpBuilderReleases#109]
Hi Rick, I am used to seeing your face on a lot of articles I've read, many of which have been beneficial to me personally as well as my business.  I haven't purchased your product because of crashing issues and I wanted to assure it could meet my needs.  It is a one of a kind product in terms of what I need but I ran into an issue using the console version:

HelpBuilderConsole.exe BUILDPROJECT -p".."

Error: Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'wwReflection20, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at HelpBuilderConsole.wwHelpConsole.BuildProject(HelpCommandLineParser parser)
   at HelpBuilderConsole.wwHelpConsole.Main(String[] args)

I did notice wwReflection20.dll in the bin folder so I tried adding the bin folder to my path but to no avail.

I am committed to using this product if I can get through a few of these hiccups.  I hope you can help me get there.

Sincerely, Ken.
ken.netherland@cloudideaas.com
480-603-8930

**Comment by RickStrahl** [comment]
Hi Ken - thanks for reporting. Let me take a look and see what's happening with the CLI code. It's been neglected for a long time, although the error you're seeing seems odd. Does the app run when you run interactively (because it's using the same libraries).

**Comment by kennetherland** [comment]
Hi Rick, I got it to work by simply moving wwReflection20.dll from the bin folder to the same folder as the CLI (up one level).
Thanks for the quick response.

**Comment by kennetherland** [comment]
sorry.. not move.. copy

**Comment by RickStrahl** [comment]
Ah - yeah I see what the problem is here. The CLI doesn't have the private bin path adjusted to the bin folder so it's not looking there for the assemblies. I'll get that fixed. Thanks.

**Comment by kennetherland** [comment]
Thank you Rick.  I just showed my wife how famous you are since you show up in my searches at least 1000 times over the years.  I went ahead and bought your product by the way, even though its written in FoxPro... ;).

**Comment by RickStrahl** [comment]
LOL!

Yeah it's getting long in the tooth for sure. I've been working on KavaDocs which is an integration tool for Markdown Monster but I just haven't had the time to build it out and finish it to put it out as a product. In the meantime I'm still writing all of my docs in Help Builder still...

Aloha,

**Comment by RickStrahl** [comment]
Fixed for the next version.

Note when the next version rolls around you should delete wwReflection20.dll in the root folder. In fact all DLLs except:

* hunspell86.dll
* dzip32.dll

Everything else should be in the `bin` folder.

There are also some command line switch updates for building including running the project after building and not building a CHM.

```text
Commands:
---------
HELP || /?      This help display           
RESET           Resets the Html Help Builder configuration file
                so that no project is loaded on startup.
                Use if a help file has become corrupt and won't open.

Reindex         -p ""ProjectFile""
                Packs and reindexes a Html Help Builder project file.

BuildProject    -p ""ProjectFile"" -nochm
                Builds a project by creating HTML, TOC, Index and 
                final CHM output files.

AssemblyImport  -a ""AssemblyFile"" -p ""ProjectFile"" -ip -ii -im
                Imports one or more assemblies and 

WebServer       -p ""WebProjectFilesPath"" -port PortNumber -v|verbose
                Serves a Help Builder project through a Web Server 
                using Windows built-in HttpListener. The -port parameter
                is optional. -v displays each URL accessed.                

RegisterHttpPort -port PortNumber
                Registers an HTTP port for WEBSERVER access. 
                Requires Administrator rights and will ask to elevate.

Options:
--------
-p          Full path to a project file. For ASSEMBLYIMPORT the 
            project file doesn't have to exist. For WEBSERVER this
            is the path to the Web folder from which to host 
            the Web server

BuildProject Options:
---------------------
-nochm      Don't generate a CHM file
-openweb    Open generated Web site in browser (runs local Web Server)
-openfolder Opens the project folder in Explorer

Assembly Import Options:
------------------------
-a          Assembly file to import for AssemblyImport
-ip         Import Protected members for AssemblyImport
-ii         Import Inherited members for AssemblyImport
-chm        Build and create CHM file

Examples:
---------
HelpBuilderConsole Reset
HelpBuilderConsole Reindex -p ""c:\help files\hostingdoc\hostingdoc.hbp""
HelpBuilderConsole BuildProject -p c:\temp\hostingdoc\hostingdoc.hbp
HelpBuilderConsole AssemblyImport -a c:\temp\wwutils.dll
                             -p c:\temp\docs\wwutils.hbp -ii -ip -chm
HelpBuilderConsole WebServer -p ""c:\WebOutput\MyProject"" -port 64101 -v
HelpBuilderConsole RegisterHttpPort -port 5101  
```

**Comment by kennetherland** [comment]
Thank you Rick!
