### ISSUE TITLE
Enhancement request:  suppress topic inclusion via some property/directive

### ISSUE THREAD

**Issue by rikaye** [RickStrahl/HelpBuilderReleases#110]
Here's my use case. I have my beautiful WWHB documentation project. In that project I have a top level topic branch for works in progress. When I have a new article or FAQ that I want to work on I add it as a child to that section. Now I know I can uncheck it in step 2 of the build output wizard but I'm lazy. I want to have some way to set a not for publication attribute of a topic, and then when I build the appropriate box will not be checked automagically.

![image](https://user-images.githubusercontent.com/28717887/97912343-ad5f6f00-1d1a-11eb-92ee-5dd4c04465ef.png)

**Comment by RickStrahl** [comment]
There is that already (sort of). 

![image](https://user-images.githubusercontent.com/1374013/97915033-e1c03480-1cf4-11eb-9db9-0e4dac61f6de.png)

This will prevent the topic from getting into the TOC, although the topic itself will still be in the help file.

**Comment by rikaye** [comment]
I'll try that out and see how it goes. Thanks, Rick.

**Comment by rikaye** [comment]
If I understand you correctly, this doesn't really do what I want which is to keep the WIP top level node and all its children out of the build process.

Well you did say in the 5.30 release topic on the board you wanted enhancement requests... ;-)

**Comment by RickStrahl** [comment]
It should - if you mark the top node as 'Don't show' it won't show that nor any of its child topics in the **published** TOC.
