### ISSUE TITLE
Add spell check entire project option

### ISSUE THREAD

**Issue by rikaye** [RickStrahl/HelpBuilderReleases#111]
I know I could dump the whole thing out to Word or PDF but it would be nice to be able to have WWHB iterate through all topics and check for spelling.

**Comment by RickStrahl** [comment]
Would be nice, but it's not really all that useful. It would result in way too many errors to display and make useful. Plus spell checking results in quite a lot of false positives or missed negatives. 

IAC, not going to add this at this late stage in Help Builder.
