### ISSUE TITLE
Crash trying to use "EDIT > Paste HTML as Formated HTML"

### ISSUE THREAD

**Issue by TomGreen1943** [RickStrahl/HelpBuilderReleases#113]
#### Error Message:
Variable 'PLUSEPRAGMALINES' is not found.

#### Module: 
PROCEDURE WWHELPFORM.OHELP.FORMATHTML C:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\WWHELP.VCT

#### Line:
24

#### Call Stack:
1. c:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | C:\Program Files (x86)\West Wind Html Help Builder\wwhelpmain.prg (292) |

----
2. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.timer | c:\program files (x86)\west wind html help builder\wwhelp.vct (30) |
   thisform.DoEditOperation(lcName)
----
3. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | c:\program files (x86)\west wind html help builder\wwhelp.vct (648) |
   		loEditBox.SELTEXT = THISFORM.oHelp.FormatHTML(_CLIPTEXT,.T.)
----
4. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.ohelp.formathtml | c:\program files (x86)\west wind html help builder\wwhelp.vct (24) |
         poMarkdownParser.CreateParser(.t.,plUsePragmaLines)
----
5. errors.fxp | ON...  | C:\Program Files (x86)\West Wind Html Help Builder\errors.prg (120) |

----

#### Window:
WWHELPFORM

**Comment by RickStrahl** [comment]
Any more info on how you got here?

**Comment by TomGreen1943** [comment]
Hi, Rick.  Thanks for following up.

 

Here is what I did.  Hope it helps!

 

ATTEMPT 1

1.	I have an empty HelpBuilder topic open in edit mode, marked as Markdown format, and [x]External link checked.
2.	I open the attached document in MSWord. Select all, and copy all (Ctrl-C) to the clipboard
3.	I go to helpbuilder, select the text edit area, and press CTRL-V.
4.	Help builder crashes.

 

ATTEMPT 2

1.	(Same as above)
2.	(Same as above)
3.	From the help builder edit menu I click on Paste HTML as formatted HTML
4.	Error message I get is below:

An unexpected error has occurred during the operation of Help Builder. The following error information is available: 



Variable 'PLUSEPRAGMALINES' is not found.
System Error # 12 

The error has been logged and you can now do one of the following:

*         Continue running the application 

*         Exit the application

*         Report the problem to us on our GitHub Repository

The bug report is below:

 

#### Error Message:

Variable 'PLUSEPRAGMALINES' is not found.

 

 

#### Error Number: 12

 

#### Module: 

PROCEDURE WWHELPFORM.OHELP.FORMATHTML C:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\WWHELP.VCT

 

#### Line:

24

 

#### Call Stack:

1. c:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | C:\Program Files (x86)\West Wind Html Help Builder\wwhelpmain.prg (292) |

 

----

2. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.timer | c:\program files (x86)\west wind html help builder\wwhelp.vct (30) |

   thisform.DoEditOperation(lcName)

----

3. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | c:\program files (x86)\west wind html help builder\wwhelp.vct (648) |

                                loEditBox.SELTEXT = THISFORM.oHelp.FormatHTML(_CLIPTEXT,.T.)

----

4. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.ohelp.formathtml | c:\program files (x86)\west wind html help builder\wwhelp.vct (24) |

         poMarkdownParser.CreateParser(.t.,plUsePragmaLines)

----

5. errors.fxp | ON...  | C:\Program Files (x86)\West Wind Html Help Builder\errors.prg (120) |

 

----

 

 

#### Window:

WWHELPFORM

 

Tom Green

514-952-0419

Carver Technologies Inc.

Umana

tom.green@umana.ca <mailto:tom.green@umana.ca> 

tom.green@carvertechnologies.com <mailto:tom.green@carvertechnologies.com>

**Comment by RickStrahl** [comment]
I haven't been able to duplicate this any which way I tried. Anything pasted from Word on my end comes in as plain text from the clipboard.

I think this might be a version issue. We did have problems with paste operation a few versions back. Try installing the latest version from the Web site and see if that fixes your issue.

**Comment by TomGreen1943** [comment]
Thanks for your effort, Rick.

 

I reinstalled Help Builder from the latest download, and it seems to have
solved the problem. I can no longer reproduce it.  Case closed.

 

Have a Merry Christmas !!

 

Tom Green

514-952-0419

Carver Technologies Inc.

Umana

tom.green@umana.ca <mailto:tom.green@umana.ca> 

tom.green@carvertechnologies.com <mailto:tom.green@carvertechnologies.com>

**Comment by TomGreen1943** [comment]
Hi Rick,

 

I like the way the preview window and the main window - both desktop windows
are linked and move together.

 

Is that a VFP functionality (and if so what is it), or did you have to
program that manually? 

I can see a nice use for it in our APP.

 

Thanks!

 

Tom Green

514-952-0419

Carver Technologies Inc.

Umana

tom.green@umana.ca <mailto:tom.green@umana.ca> 

tom.green@carvertechnologies.com <mailto:tom.green@carvertechnologies.com>

**Comment by RickStrahl** [comment]
It’s custom, but it’s pretty simple. Just track the resize events on the main form and move the other window. It’s a few events - resize, activation, min/max operations
