### ISSUE TITLE
Error when attempting to use the remove unreferenced images tool

### ISSUE THREAD

**Issue by rikaye** [RickStrahl/HelpBuilderReleases#117]
#### Error Message:
Invalid path or file name.

#### Module: 
PROCEDURE FRMORPHANEDIMAGES.FINDORPHANEDRESOURCES C:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\CODE\REMOVEUNREFERENCEDIMAGES.SCT

#### Line:
34

#### Call Stack:
1. c:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | C:\Program Files (x86)\West Wind Html Help Builder\wwhelpmain.prg (318) |

----
2. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.otoolbar.click | c:\program files (x86)\west wind html help builder\wwhelp.vct (5) |
   THISFORM.tmrToolbar.SetTool(Tool)
----
3. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.settool | c:\program files (x86)\west wind html help builder\wwhelp.vct (29) |
   thisform.DoEditOperation(lcName)
----
4. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | c:\program files (x86)\west wind html help builder\wwhelp.vct (541) |
   	    DO form RemoveUnreferencedImages
----
5. c:\program files (x86)\west wind html help builder\code\removeunreferencedimages.sct | frmorphanedimages.cmdsearch.click | c:\program files (x86)\west wind html help builder\code\removeunreferencedimages.sct (6) |
   thisform.txtOrphanedFiles.Value = thisform.Findorphanedresources(goHelp.oHelp.cProjPath,"wwhelp")
----
6. c:\program files (x86)\west wind html help builder\code\removeunreferencedimages.sct | frmorphanedimages.findorphanedresources | c:\program files (x86)\west wind html help builder\code\removeunreferencedimages.sct (34) |
   	lnFiles = ADIR(laFiles,lcPath + "*.*","",1)
----
7. errors.fxp | ON...  | C:\Program Files (x86)\West Wind Html Help Builder\errors.prg (120) |

----

#### Window:
FRMORPHANEDIMAGES

**Comment by rikaye** [comment]
Looks like the locked file situation may be root cause for this one as well. I was able to run this against my copied project.

**Comment by RickStrahl** [comment]
Ok going to close this. I use this all the time without issues.

File access problems  will cause all sorts of problems and break just about all aspects of Help Builder.
