### ISSUE TITLE
Set Desktop .T. for Search dialog

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#12]
By setting Desktop to .T., the Search Topics dialog can be moved outside the HTML Help Builder window, which is useful because a lot of times I'll leave it open, go to the first topic in the Search Topics list, edit the text, go the second topic in the list, and so on. As it is now, the dialog takes up space and is always on top, making it challenging to leave it open but out of the way.

**Comment by RickStrahl** [comment]
Good idea. I seem to remember that I tried that before and there were some issues, but there have been a bunch of changes to the way the UI works better non-modally so this might work better now.

**Comment by RickStrahl** [comment]
Done. It'll be in the next drop. Also cleaned up the preview browser with similar behavior. 

Let me know how this works or if you run into any issues with the window open.

The search box has (like all popup forms that pop ontop of the new editor but are fine from other controls) has some focus issues when activated from the editor - you have to click on the editor window to get focus. Still haven't found a good solution to this issue unfortunately short of using timers to delay activation and focus setting.
