### ISSUE TITLE
Norton picked up suspicious file during installation of trial software

### ISSUE THREAD

**Issue by mannear** [RickStrahl/HelpBuilderReleases#126]
Hi,
I was about to trial your software when Norton picked up a suspicious file during the installation and stopped further activity. See screenshot below of Norton's report
![Stop](https://github.com/RickStrahl/HelpBuilderReleases/assets/38301281/dd339802-4da7-45de-997a-3d2f27b875e4)

I would like to use your software, but these days one cannot be too careful. Please advise

Regards
Michael Annear

**Comment by RickStrahl** [comment]
Thanks for the report but I have no idea what it's complaining about so not really anything I can look into.

AV Software is full of false positives.
