### ISSUE TITLE
Error when Importing SQL Server Database

### ISSUE THREAD

**Issue by DeltonLee** [RickStrahl/HelpBuilderReleases#13]
Using the Beta 5.0.102, I get an error when attempting to import all tables in a SQL Server database, "The specified Key already exists."  This database has multiple tables that have the same name that exist in separate schemas within the same database, and I believe this is what is causing the error.  If I ignore the error each time I see it, the import eventually completes and each table has a subtopic under the database topic (but the duplicates are listed only once and the schema names are not shown).  My suggestion is to create a subtopic for each schema for tables, stored procedures, etc.

![hb error](https://cloud.githubusercontent.com/assets/3245477/10002729/d22b607a-6076-11e5-9a22-84b389e8ad85.jpg)

**Comment by RickStrahl** [comment]
Hmmm... that's kind of an unusual scenario especially with duplicated tables in different schemas. 

I don't think we'd typically want to isolate out database imports by schema. Rather I think we'd want an option to specify which scheme to import...

**Comment by DeltonLee** [comment]
An option to specify each schema separately would be fine, and I could import each individually.  Since schemas are essentially containers, ideally I would want to have a subtopic for each schema and have the associated objects under the subtopic for each schema.  In any case, the database importing is a nice feature of the product.

**Comment by RickStrahl** [comment]
Ok, so I implemented schema supported in the latest build (5.0.117-beta). 

When you import a complete database it segments tables out by schema now so you get dbo.table1 and app.table1.

This is still a bit rough so give this a try. Stored procs currently are not respecting schemas so if there are dupes there that will still fail.
