### ISSUE TITLE
Dragging topic from one project to another doesn't work

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#14]
This used to work because I use it all the time: open two Help Builder projects and drag a topic from one project's TreeView to a header topic in the other project. The topic isn't added to the second project.

**Comment by RickStrahl** [comment]
Hmmm... that should stil work. Just double checked works for me.

One thing - try making sure that you activate a Fox control before moving into the tree view. There are some odd focus issues with the Web Browser control that can cause focus to not work as expected and that might be what's interfering.

Are you seeing the drag icon and do you see it all the way over to the second instance?

**Comment by DougHennig** [comment]
Yup, I see the drag icon. It appears as no drop until I'm over a node in the second project's TreeView and then it appears as drop. It looks like it works except the topic doesn't get added to the second project. I opened it as a table to confirm the record wasn't added. I hadn't clicked on the web browser control in either window, just the TreeView in the first project and didn't click at all in the second after opening it.

**Comment by RickStrahl** [comment]
Not sure then. Nothing has really changed with this code in a long time. It works for me - it looks like the D&D is working since you see the drag and drop icons properly. 

I can take a look next week when I see you.

**Comment by RickStrahl** [comment]
I'm going to close this since I can't repro this for now. If you could check with newer versions and let me know if this continues to fail I'll take another look. I reviewed the code and I don't see what could be causing this to not work especially without a failure of some sort.

**Comment by DougHennig** [comment]
I tried it with a couple of topics in version 120 and it seems to work now. Weird!
