### ISSUE TITLE
Error clicking file button in Add-In Manager

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#15]
Create a new add-in and click the button with the ellipsis for File Name. The first time I do this, I get "File access is denied 00000001: Incorrect function". Clicking Ignore gives "Invalid path or file name". Clicking Ignore for that then displays the Select Addin file dialog. The second time doing this gives a slightly different first error message, just "File access is denied".

**Comment by RickStrahl** [comment]
Add-in functionality has been temporarily removed.

Are you actually trying to create an add-in? I have yet to hear of anybody using add-ins and I was considering pulling the functionality out.

**Comment by DougHennig** [comment]
Yes, I use one add-in: it changes a couple of things, generates the CHM, and copies it up one folder since that's my normal folder structure. I've used it for years so I wouldn't normally have used this dialog, but I was practicing my Plugins session for SWFox next week and I show how Help Builder implements plugins as an example.

**Comment by RickStrahl** [comment]
Ok so I took a look. There may be a couple of issues.

First, create an \AddIns folder underneath the Help Builder installation folder. That folder is not getting installed right now and that's causing the main issue with the first error you saw.

I'll fix that in the next build by making sure that the Addins Folder gets installed.

The other related issue is that you can't write out a new addin file and can't compile a PRG file in place right now, **unless** you run as Administrator.

For a demo for now you can maybe mark the Help Builder shortcurt to `Run as Administrator`. 

This will need to be fixed, but it's a bigger fix than what I have time for before the conference.

**Comment by RickStrahl** [comment]
Ok I have a workaround for this after all. 

Fixed in Version 5.0.120-beta.
