### ISSUE TITLE
Error turning on VS Integration

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#16]
In the Administration tab of the Options dialog, I turned on Visual Studio 2012 and immediately got an error dialog with error #1 file does not exist.

**Comment by RickStrahl** [comment]
Currently plug-in functionality doesn't work. For Visual Studio 2015 the old plug-in won't work because the old Add-in format is no longer supported by Visual Studio. 

I'm planning on adding back support for Visual Studio 2015, but it probably will happen after Help Builder 5.0 is released.
