### ISSUE TITLE
.NET import issue with method accepting Func

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#17]
I have a .NET class with the following method:

public bool Any(Func&lt;IField, bool&gt; predicate)

After import, Parameters in the Class Info page has this:

**Func<IField (closing asterisks removed so Markdown isn't used in Github)

**Boolean> predicate (closing asterisks removed so Markdown isn't used in Github)

I can see that this would be tough to parse since the comma appears in the parameters for the Func rather than for the method.

**Comment by RickStrahl** [comment]
Fixed.
