### ISSUE TITLE
Extra lines and spaces in Parameters after .NET import

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#18]
I have a .NET class with XML comments for a method like this:

```
    /// <param name="array">
    /// The array to copy to.
    /// </param>
    /// <param name="arrayIndex">
    /// The starting index.
    /// </param>
```

After importing, the Parameters in the Class Info has this (closing asterisks removed so Markdown not used in Github):

**array**  
The array to copy to.
(12 spaces followed by carriage return)
(blank line)
**arrayIndex**  
The starting index.
(12 spaces followed by carriage return)
(blank line)
(blank line)

This isn't a huge deal since it renders correctly but means removing some spaces and blank lines if I want to add anything.

**Comment by RickStrahl** [comment]
So the behavior is to have a couple of blank lines after each parameter. That won't go away other than the last parameter.

The spaces are now being trimmed properly - not really sure where those are coming from - I guess it must be from the XML comment somehow, but they're now getting stripped.

**Comment by DougHennig** [comment]
Still getting the line with the 12 spaces but the blank lines after the last parameter are now gone. Again, no biggie.
