### ISSUE TITLE
Object is not contained in a FORM (#1938) error

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#19]
This doesn't happen all the time but often enough that it's mostly reproducible.

I select a topic imported from a .NET class, then choose Topic Edit View, click the Class Info tab, and click in the Parameters editbox. I then click the Topic HTML View button and this error occurs.

**Comment by RickStrahl** [comment]
Are you running the latest version? There have been some fixes around this and it's happening a lot less now.  It's a nasty .Destroy() timing issue related to the ActiveX controls releasing at random times after the form is already released and THISFORM is no longer valid.

Current version up there is .120.

**Comment by DougHennig** [comment]
Yes, that's the one I'm using.

**Comment by RickStrahl** [comment]
Fixed. Thanks for the detailed repro case.
