### ISSUE TITLE
Remove West Wind logo from header_template.wcs

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#22]
Remove this from header_template.wcs in all supplied template folders:

```
<img src="images/logo.png" class="banner-logo" /s>
```

I know how to do this but likely most people would have to poke around for a while to discover where the logo is defined, especially since header_template.wcs doesn't show up in the Modify Theme dialog.

**Comment by RickStrahl** [comment]
No - the idea with this is that there's a generic logo.png file that you can replace with your own squarish logo and replace our logo. Hoping to get people to add a visual element to their header so it looks nice - and if not, well the help builder icon works as a generic documentation icon. 

The header and footer are templates meant to be customized. 

Tip: To get to the template modify menus, go to the tree and select any topic, then Edit Topic Templates | Edit Topic Template which edits the template for the active topic. On that menu you also have options to edit the header and footer topics.

**Comment by DougHennig** [comment]
Fair enough.
