### ISSUE TITLE
Angle brackets not rendering properly

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#23]
I have a class that appears like this in the Syntax editbox on the Class Info page:

public abstract class MetaDataCollection&lt;TItem&gt; : BasePersistedCollection&lt;TItem&gt;, IMetaDataCollection&lt;TItem&gt;

It appears like this when rendered:

public abstract class MetaDataCollection : BasePersistedCollection, IMetaDataCollection

If I manually change the angle brackets to &lt and &gt, it renders correctly.

**Comment by RickStrahl** [comment]
You probably need to update your templates. The updated templates should encode the html.

The updated templates should have something like this for Syntax:

``` html
<% IF !EMPTY(oHelp.oTopic.Syntax) %>
<pre class="syntaxbox" id="syntax">
<%= EncodeHtml( oHelp.oTopic.Syntax ) %>
</pre>
<% ENDIF %>
```

**Comment by DougHennig** [comment]
Ok, I updated my templates. Interfaces.wcs uses EncodeHtml (see issue #24 for a bug with that) but others, like ClassHeader.wcs, still use oHelp.FormatHtml. I checked the originals in the Template\MSDN (and other subdirectories) of the program folder and they're the same way (which I expected since I updated the project templates).

**Comment by RickStrahl** [comment]
I think the MSDN template hasn't gotten updated. I work on the default template and then update the others when I remember :-)

All of the syntaxviews should be the same and the code above should be what they are in all templates.

**Comment by RickStrahl** [comment]
I've pushed out another new version (.148) today that has updated templates. Hopefully that'll do the trick for you.
