### ISSUE TITLE
Typo in Interface.wcs

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#24]
This line:

<%= oHelp.EncodeHtml( oHelp.oTopic.Syntax ) %>

should be:

<%= oHelp.FormatHtml( oHelp.oTopic.Syntax ) %>

**Comment by DougHennig** [comment]
Hmm, I see you used EncodeHtml on purpose. However, using EncodeHtml, I get next to no content. This is what I get with FormatHtml:

![format](https://cloud.githubusercontent.com/assets/12052409/11383429/b6801972-92cd-11e5-8d0e-c6c979685f52.png)

This is what I get with EncodeHtml:

![encode](https://cloud.githubusercontent.com/assets/12052409/11383431/b99a9a88-92cd-11e5-95c2-309847419299.png)

**Comment by DougHennig** [comment]
OK, I see the problem: the template has oHelp.EncodeHtml but it should be just EncodeHtml. That works correctly.

**Comment by RickStrahl** [comment]
Fixed in the stock templates as well. Thanks.
