### ISSUE TITLE
Error importing .NET assemblies

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#25]
In 5.0.143, I'm getting the following error importing most of my .NET assemblies, including those I could import with the previous build:

Import failed:
OLE IDispatch exception code 0 from mscorlib: Derived classes must provide an implementation...

**Comment by RickStrahl** [comment]
Sigh. Yup a regression bug from the Generic method import changes. Was able to duplicate and fixed for .148.
