### ISSUE TITLE
How to format example as code?

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#27]
I have the following in Example for a class header:

<pre>// This example is taken from the Sample WinForm Application sample.

private void GetTags(ITag parentTag)
{
   List&lt;ITag&gt; tags;

   // If a parent tag wasn't specified, get all top-level tags.
   // Otherwise, get the child tags for the specified parent tag.
   if (parentTag == null)
   {
      tags = app.ReportEngine.Tags
         .Where(t => t.ParentTag == null)
         .OrderBy(t => t.Name).ToList();
   }
   else
   {
      tags = app.ReportEngine.Tags
         .Where(t => t.ParentTag == parentTag)
         .OrderBy(t => t.Name).ToList();
   }
   return tags;
}</pre>

When I add a PRE tag around it, indents are lost, List&lt;ITag&gt; tags; appears as List tags;, and there are extra blank lines.

![example](https://cloud.githubusercontent.com/assets/12052409/11484577/625ad930-9774-11e5-864c-46a33498b642.png)

How can I format the example so looks like it does in the Example editbox?

**Comment by RickStrahl** [comment]
Use triple back ticks, plus the language:

``````
```csharp
// your code goes here
```
``````

Works with any language.

if you don't do anything you should get formatted code without syntax coloring.

Also note that the formatting for code fields should be:

``` html
<% IF !EMPTY(oHelp.oTopic.Example) %>
<h3 class="outdent" id="example">Example</h3> 
<%= oHelp.FormatExample(oHelp.oTopic.Example)%> 
<% ENDIF %>  
```

Note no PRE tags.

**Comment by RickStrahl** [comment]
Actually just checking the behavior I see that if you put no formatting into it will just render the text, which is not correct.

What should happen is:
- If no markup is provided it should render as plain code (no syntax coloring)
- if ``` exist it'll render plain using markdown formatting.

This is a bug.

**Comment by RickStrahl** [comment]
Fixed for next release.
