### ISSUE TITLE
XML comments not imported

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#28]
I have a class with a couple of methods that didn't have their XML comments imported. I can't see anything different about these methods. Here's one of them. The Main page is empty and the Class Info page has nothing at all in Parameters:

```
    /// <summary>
    /// Copies the collection to the specified array starting from the specified index.
    /// </summary>
    /// <param name="array">
    /// The array to copy to.
    /// </param>
    /// <param name="arrayIndex">
    /// The starting index to copy from.
    /// </param>
    public virtual void CopyTo(TItem[] array, int arrayIndex)
    {
        _collection.CopyTo(array, arrayIndex);
    }
```

The other is an event. Again, the Main page is empty:

```
    /// <summary>
    /// Raised when the collection is changed.
    /// </summary>
    public event NotifyCollectionChangedEventHandler CollectionChanged;
```

**Comment by RickStrahl** [comment]
Ugh - that's a tough one it turns out. Surprised I haven't run into this before, but it has to do with the generic type definition on the parent not mapping to the method signature in the XML docs. The problem is I can't find a way to properly map the parent generic type to index written in the XML docs.

**Comment by RickStrahl** [comment]
Give this another try in .175. I've fixed a number of signature parsing bugs (thanks - this actually ended up fixing a number of other problems) related to generic types and generic array parameters in particular.

**Comment by DougHennig** [comment]
In 180, I now get "OLE IDispatch exception code 0 from mscorlib: Method may only be called on a Type for which Type.IsGenericParameter is true..." when importing the assembly. Would having a copy of the assembly and the XML file help?

**Comment by RickStrahl** [comment]
Yes probably. But I'll also need any dependencies you have on that assembly.

BTW - thanks so much for pointing out these things. A lot of very minor bugs have been fixed thanks to your reports. I'm introducing bigger ones it seems :-) but the crashes are easy to fix actually once I have a repro case.

The tricky thing is there are so many variations of how things can be defined - it's impossible to think of all the tests to set up for this.

thanks.

**Comment by DougHennig** [comment]
The attached is really a zip file so rename it. For some reason, when I dragged it here, GitHub said it didn't support this file type. The assembly to import is Collections.dll; let me know if I missed any dependencies.

[Release.txt](https://github.com/RickStrahl/HelpBuilderReleases/files/61676/Release.txt)

I'm sure this is tricky: looking at code, the IL, and the XML comments, I can see it's a nightmare to parse!

**Comment by RickStrahl** [comment]
Thanks. That helps. Fixed a number of additional issues. It now builds, but there are still a few odds and ends that don't import the XML docs. Specifically generic ref and value types don't work - getting the signature wrong. Not sure how to get the generic type info on these value - need to experiment. Generic Reflection is an insane mess of inconsistency - yet surprising that it works at all.

Try .181.

**Comment by DougHennig** [comment]
Fixed in 190.

**Comment by RickStrahl** [comment]
Doug - thanks again for letting me look at your lib - it's a great sample of a bunch of weird generic combinations. As I mentioned there are a few other things that are open in this respect - feel free to post those preferrably one issue at a time.
