### ISSUE TITLE
MarkDown topic with html table hangs

### ISSUE THREAD

**Issue by zdenekkrejci** [RickStrahl/HelpBuilderReleases#30]
Markdown topic with html table hangs and does'nt generate html page.

example:

``` html
<table class="detailtable" width="96%">
<tr>   
  <th>header1</th>
  <th>Header2</th>
</tr>
<tr>
  <td>1</td>
  <td>2</td>
</tr>
<tr>
  <td>3</td>
  <td>4</td>
</tr>
</table>
```

The last version which works is 1.20.

**Comment by RickStrahl** [comment]
Thanks for reporting this - strange regression bug in a  parsing routine that actually affected a number of other operations.Fixed and will be in releases post .198.

**Comment by RickStrahl** [comment]
Updated in .199 which is online now. Thanks again.

**Comment by zdenekkrejci** [comment]
Yes i works correctly now. Thanks.
