### ISSUE TITLE
Generate word document with codepage

### ISSUE THREAD

**Issue by zdenekkrejci** [RickStrahl/HelpBuilderReleases#32]
We have project with codepage 1250 (Czech language).

MS Word document generated from WW HTML Help Builder is not correct for some national characters. 
HB creates file with extension HTML which has no charset and lanuage set.
When we modify this .HTML file, import into Word is OK.
Example:

``` html
<html lang="cs-cz" xml:lang="cs-cz">
<head>
<title>Help Topics</title>
    <meta charset="windows-1250" />
```

Both of the setting could be taken from options of the project. 
1. CodePage of the project is 1250
2. Content editor spell checking dictionary is CS_CZ

Or you may add new options into project settings.

These settings could be used for all of the generated htm, html and aspx files.

Thanks for your help.

**Comment by RickStrahl** [comment]
You can change the `templates\_Layout.wcs` template and add the meta tag into your default template that is used for all topics.

Right click on a topic in the tree and select _Edit Topic Templates_ | _Edit Layout Template_.

**Comment by RickStrahl** [comment]
I believe the output generated is UTF-8 though and that should work regardless of language used so I'm not sure exactly what might be going on there. Word should recognize the UTF-8 encoding.

**Comment by RickStrahl** [comment]
One more thing - you also need to change the code page for the project in Tools | Options.

**Comment by zdenekkrejci** [comment]
1. Of course we have chaned templates. It helps for .HTM and .CHM files, but not for big  .HTML file, which is used for generating WORD document. Here is the only possibility we have found - edit the html file, add meta information and set the file read-only and generate DOC again.
2. If we install some of the new version of Help Builder, we have to update templates. In this case we have to edit templates manually  again and again.
3. Generated HTM and HTML files are not in UTF-8, but Windows-1250 in our environment.
4. The hbp project has the codepage 1250.

**Comment by RickStrahl** [comment]
Ok - so to be clear:

The generated HTML and CHM files are fine, correct? They work correctly with UTF-8 encoded content.

The Word export does not work because the content is not UTF-8 encoded.

The latter is fixed now (in Current Release build .200) - it exports for Word as UTF-8 and in a quick check with CodePage 1250 enabled and pushing a few Czech chars into the page, those characters end up in the Word document when I generate.

**Comment by zdenekkrejci** [comment]
HTM and CHM are correct with  a modified template which includes meta information about language and charset. They are not in UTF-8, but Windows-1250.

we didn't found template for HTML prepared for Word output.

My computer is set to Czech environment with codepage 1250 for non-Unicode application.
Next week I'll prepare small HBP project with some Czech chars example.

Thank you very much for your attention.

**Comment by RickStrahl** [comment]
You shouldn't have to. Just try the latest build - I think it fixes what you describe.

**Comment by zdenekkrejci** [comment]
I've made first test and it works for me fine.
All of the html files are now UTF-8 and Czech chars in Word documents is OK.
Thak you very much.
