### ISSUE TITLE
CodePage in HTML

### ISSUE THREAD

**Issue by zdenekkrejci** [RickStrahl/HelpBuilderReleases#33]
Almost all .htm files are now generated in UTF-8. 
Only files 
- keywords.htm, 
- index.htm 
- tableofcontents.htm  

are created in the code page by the project and aren't tagged charset. It would be possible to create these files also in UTF-8?

I also propose to modify search.aspx to look for files in UTF-8. 

In the function SearchFile()

``` csharp
StreamReader sr = new StreamReader(File);
```

replace with

``` csharp
StreamReader sr = new StreamReader(File,Encoding.UTF8);
```

**Comment by RickStrahl** [comment]
search.aspx and keywords.htm are currently not used and have been removed been removed in the latest build as we'll do search now on the topic tree which is faster albeit less complete. I think keywords still generate but they are not linked.

index.htm is just a regular topic now so it should be HTML encoded like all others - and looking at the output that appears to be the case.

**Comment by zdenekkrejci** [comment]
Yes you are right. We are more familiar with the new version and it works.
Thank you
Unfortunately, we did not find description of the changes between versions, so we sometimes take longer.

**Comment by RickStrahl** [comment]
No worries. I appreciate the feedback. The previous version didn't take take encoding into account at all so this is a slow conversion process finding all the issues.

It turns out that in order for things to work smoothly all the templates should be UTF8 encoded and use a BOM. With UTF-8 with BOM works correctly for page rendering and should also work correctly for tableofcontents and other static pages.

Several of the default templates do not have  BOM so they may render incorrectly.

**Comment by zdenekkrejci** [comment]
I tried to create html files in the current version 5.202
The file **tableofcontents.htm** is marked as charset="UTF-8",  but in fact contains Windows-1250.

**Comment by RickStrahl** [comment]
Try the current 5.0.205 please...

**Comment by zdenekkrejci** [comment]
I've tried it. The result is the same.
TalbeOfContens.htm has  tag meta charset="utf-8"  but the text is in Windows-1250.

**Comment by RickStrahl** [comment]
Are you sure you have re-generated the project with .205? Output is most definitely UTF-8 encoded in .205 in TableOfContents.htm.

**Comment by zdenekkrejci** [comment]
Yes I'm sure. Download and re-install .205, Read default templates. Select template MSDN. Generate web. TableOfContents has the same error. Charset UTF-8, but in fact Windows-1250. Other htm files are OK.

**Comment by RickStrahl** [comment]
Not sure then.  What is actually wrong? The template or the embedded topics or both?
Note that you also need to update your templates to see the new UTF-8 with BOM templates.

**Comment by zdenekkrejci** [comment]
Yes template has BOM. And the error is the same.
See attachment.
[TableOfContents.zip](https://github.com/RickStrahl/HelpBuilderReleases/files/82681/TableOfContents.zip)

If you change charset to Windows-1250, you'l see the right characters.

**Comment by RickStrahl** [comment]
Can you retry this in .206 please? It's working for me

![image](https://cloud.githubusercontent.com/assets/1374013/12213560/b2abcc78-b61e-11e5-9ba1-4a495f062db3.png)

One thing to make sure is that you also fully refresh the page in the browser as browsers will often cache the file encoding - a full refresh will undo the caching.

**Comment by zdenekkrejci** [comment]
The version .206 generates correct TableOfContents.htm in UTF-8.

Thank you very much.
