### ISSUE TITLE
Use Desktop for all dialogs

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#35]
Nothing critical, but some dialog should have Desktop set to .T. so they can be moved outside the Help Builder dialog window:
- Theme and Template Editor
- Import Class or Database
- Import HTML Help or HTML Workshop Files
- Sort Topics
- Create a New Project
- Create New Topic

**Comment by RickStrahl** [comment]
All Wizard forms now should be desktop forms. Address Theme and Template Editor and Sort Topics. Will be updated in post .206 release.
