### ISSUE TITLE
Changing theme doesn't do anything and can give error

### ISSUE THREAD

**Issue by FransBouma** [RickStrahl/HelpBuilderReleases#37]
Ok, after reading the help a bit, I get to know the application a bit better. As I don't like the code formatting in the default theme (no offense!) I want to change the theme. (This is on the imported CHM project)
- Clicking on 'Select theme' doesn't always open the dialog
- If it does, selecting a theme other than Darkhan, gives me a new dialog with 'current template has no name', and prompts for a name. Just clicking OK (so no name specified) works, but has no effect on the theme selection. Specifying a name however gives:

> An unexpected error has occurred during the operation of Help Builder. The following error information is available: 
> File 'c:\temp\helptemp\templates*.*' does not exist.
>  System Error # 1 
> The error has been logged and you can now do one of the following:• Continue running the application 
> • Exit the application
> • Report the problem to us on our GitHub Repository

Templates are then borked, so these have to be updated in the options dialog. I did that, but get the default theme back. So... it's not really possible (for me at least) to select another theme than the default.

**Comment by RickStrahl** [comment]
Fixed in 5.0.216

Problem was related to missing empty files, the installer failed to pick up. Changed empty files to 1 byte files to avoid possible issue in the future.
