### ISSUE TITLE
Markdown conversion doesn't do anything

### ISSUE THREAD

**Issue by FransBouma** [RickStrahl/HelpBuilderReleases#38]
After importing the topics of a .chm file into help builder, I wanted to work with markdown, but my pages are all in HTML. I open a topic in the editor, and click the M button to convert to markdown, but nothing happens. I select a different format type (HTML, Markdown, Helpbuilder format) but that too has no effect. 

Selecting the text in the editor and then pressing the convert button also has no effect, in short: converting to markdown apparently has no effect. Not sure whether this is due to the fact there's already HTML in the text, so it doesn't know whether to convert that too, but now absolutely nothing happens :)

I must say, (and this is totally related to what I have already, namely a tremendous amount of HTML based help topics, not something that's helpbuilder's fault) helpbuilder might not fit the current state of my documentation files, as they first have to be batch-converted to markdown perhaps before I can utilize the benefits of the tool, with templates etc. I usually write the docs in a wysiwyg html editor and manually manage the TOC tree.

**Comment by FransBouma** [comment]
I've tried to convert all pages using pandoc using this little helper: http://stackoverflow.com/questions/27852067/batch-convert-files-with-pandoc-in-windows, which worked great. I now have a lot of .md files which I now can use to be the documentation source inside helpbuilder instead of the htm files with the same content. Will try that tomorrow :)

**Comment by RickStrahl** [comment]
That's great...

FWIW, Help Builder includes its own HTML to Markdown converter. You can click the Markdown icon in the toolbar and it will convert the HTML to Markdown in the current topic (and switch the topic mode to Markdown). 

![image](https://cloud.githubusercontent.com/assets/1374013/12729118/3b54d0ee-c8c9-11e5-8161-78a59fd36e83.png)

If the topic type is already Markdown, it won't convert again. It only works if the topic type is Html or Html Help Builder (classic format). 

On some occasions I've seen focus issues on the menu - where the menu doesn't respond. If that's the case can you try either switching the view to HTML preview then back, or clicking on the Remarks field (on another tab) and running the Markdown button again. I'm trying to track this particular bug down, but it's very inconsistent (related to the Web browser control container and internal focus).

**Comment by FransBouma** [comment]
Hmm, that markdown button is what I meant :) It didn't do anything but perhaps I tried it already on a topic that was previously converted when 'markdown' was selected because I was toying with it. 

I'll try your suggestions tomorrow on another topic which hasn't been touched yet :)

**Comment by RickStrahl** [comment]
Focus and key issues are still outstanding, but I'm going to close this particular issue since it's addressed.
