### ISSUE TITLE
Tooltip issues in toolbar buttons

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#4]
- The tooltip for the spell checker button has "on and of" which should be "on and off"
- The tooltip for the markdown button has "Mardown"
- The button to the right of the Create List Item button (which looks like it right-aligns something) has no tooltip

**Comment by RickStrahl** [comment]
Fixed

**Comment by RickStrahl** [comment]
The 'right align' is a block quote. The way the new formatting works it's more like a callout. Use it for notes.

> #### Note
> 
> here is the note text

which writes like this (in Markdown):
`>### Note`
`>here is the note text`
