### ISSUE TITLE
Wrong location for vsizegrip.png

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#42]
wwHelp.css references '../images/vsizegrip.png' but it should be '../bmp/images/vsizegrip.png'

**Comment by RickStrahl** [comment]
Actually it's a different bug - the link is correct, but Update Templates isn't copying the file at the moment, but it gets installed with new projects.

The best thing to do for now is to copy the file to the images\ folder of your project.

I just added the logic to copy the file to the correct folder on template updates as well.

Thanks.
