### ISSUE TITLE
Search problem

### ISSUE THREAD

**Issue by tonytomov** [RickStrahl/HelpBuilderReleases#47]
Hello,

I can not configure HTML search to work. Does it require a ASP for this purpose?
The docs say that ASP is needed: https://helpbuilder.west-wind.com/docs/_1ho064dpi.htm , but when I build the HTML the dialog is quite different.

Can you please advice how to resolve this.

Thank you

**Comment by RickStrahl** [comment]
The search page is no longer supported in Help Builder 5.0. We removed that in favor of the quick search bar - it's not as complete but much more usable for finding content effectively.

FWIW, Help Builder still generates the search page I think, it's just not linked.

The Help Builder Documentation ironically is very much out of date, which is one of the last things left to do before getting Help Builder 5.0 to release.

**Comment by tonytomov** [comment]
Does the quick search bar depend on ASP? 
When you expect to finish this? I see it in your home page, but it does not find anything (or almost)
My question is: Can we search within a text marked as javascript/php/asp and etc code?

**Comment by RickStrahl** [comment]
No the search bar uses client side searching of the topics displayed in the tree. It only works off the title.

For deep searching on your site I recommend you let Google handle that for you.
