### ISSUE TITLE
Show tables in alphabetical order

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#49]
Another picky one: when you import a database, show the combobox of tables in the database in alphabetical order. Otherwise, it's hard to find the one table you want.

**Comment by RickStrahl** [comment]
This is really old, but looking at it now: Where are you referring to this? What dropdown?

**Comment by DougHennig** [comment]
When you choose "SQL Server Table" as the thing to import and enter a connection string, you next get a "Table Import" dialog with a list of tables in the database but the table list isn't in alphabetical order.

**Comment by RickStrahl** [comment]
This has been finally fixed. Also affects the order of tables imported when importing all tables.
