### ISSUE TITLE
Problem with Snagit 13

### ISSUE THREAD

**Issue by JaeggiGerhard** [RickStrahl/HelpBuilderReleases#54]
#### Error Message:

Klassendefinition SCREENCAPTURE wurde nicht gefunden.
#### Module:

PROCEDURE WWHELPFORM.DOEDITOPERATION E:\WWAPPS\WWHELP\WWHELP.VCT
#### Line:

559
#### Call Stack:
1. e:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | E:\Program Files (x86)\West Wind Html Help Builder\wwhelpmain.prg (285) |

---
1. e:\wwapps\wwhelp\wwhelp.vct | wwhelpform.tmrtoolbar.timer | e:\wwapps\wwhelp\wwhelp.vct (30) |
   thisform.DoEditOperation(lcName)
   ----
2. e:\wwapps\wwhelp\wwhelp.vct | wwhelpform.doeditoperation | e:\wwapps\wwhelp\wwhelp.vct (559) |
       loCaptureForm = CREATEOBJECT("ScreenCapture",THISFORM,.T.)
   ----
3. errors.fxp | ON...  | E:\Program Files (x86)\West Wind Html Help Builder\errors.prg (120) |

---
#### Window:

WWHELPFORM

**Comment by RickStrahl** [comment]
Yes - this is a bug with SnagIt and there is currently no workaround. I've been working with the SnagIt folks and they've acknowledged the issue - no word on when they are fixing this as this is apparently a low priorty bug to them.

**Comment by RickStrahl** [comment]
FWIW this was fixed with recent SnagIt releases. I believe it was SnagIt 13.1.2 that fixed this issue.
