### ISSUE TITLE
Copy Files for web

### ISSUE THREAD

**Issue by zdenekkrejci** [RickStrahl/HelpBuilderReleases#55]
it would be possible change the dialogue "Help Compile Results"?
I would like a new button "Copy files for web", wich copies new version of web files to some directory in local network. The path could be se in Tools / Options.

Thanks you Zdeněk Krejčí

**Comment by RickStrahl** [comment]
The closest thing for this is to export to a Zip file - you can then take the zip file and unpack it in the desired location.

**Comment by zdenekkrejci** [comment]
It woks fine. Thank you.
