### ISSUE TITLE
Using wwHelp_keys - Variable 'GCVERSION' is not found.

### ISSUE THREAD

**Issue by EdwardTheGreat** [RickStrahl/HelpBuilderReleases#57]
I am using Trial version 5.0.235
I ran do wwHelp_keys and then any of the functions I try to use thru the hotkeys or the wwHelp menu generate the same error message (which appears to be generated from within the west wind help builder application.)

#### Error Message:
Variable 'GCVERSION' is not found.

#### Module: 
PROCEDURE WWHELPFORM.OHELP.OPEN C:\WWAPPS\WWHELP\WWHELP.VCT

#### Line:
101

#### Call Stack:
1. c:\wwapps\wwhelp\wwhelp.vct | wwhelp.openform | c:\wwapps\wwhelp\wwhelp.vct (21) |
      THIS.oForm = CREATEOBJECT("wwHelpForm",lcFilename)
----
2. c:\wwapps\wwhelp\wwhelp.vct | wwhelpform.init | c:\wwapps\wwhelp\wwhelp.vct (93) |
   IF !THIS.Open(,,.T.)  && Silent Operation
----
3. c:\wwapps\wwhelp\wwhelp.vct | wwhelpform.open | c:\wwapps\wwhelp\wwhelp.vct (40) |
   IF !THISFORM.oHelp.Open(lcFileName,.t.,llSilent)
----
4. c:\wwapps\wwhelp\wwhelp.vct | wwhelpform.ohelp.open | c:\wwapps\wwhelp\wwhelp.vct (101) |
      IF TRIM(wwHelp.Scope) # gcVersion
----
5. errors.fxp | ON...  | c:\progra~2\westwi~1\errors.prg (120) |

----

#### Window:

After I exit that error, the developer environment of foxpro I am running gives this error:
(If I had pressed Shift-F1) it shows error on line 158 gowwHelp.OpenForm()
OLE IDispatch exception 0 from ?: :..

**Comment by EdwardTheGreat** [comment]
Error still happens with paid version.
Can also reproduce error with:
oHelp=createobj("wwHelp.wwHelp")
oHelp.Open("c:\helpdoc\helpdoc.hbp",.t.)

**Comment by RickStrahl** [comment]
Sorry - there were a number of issues with the COM server implementation. These are addressed in 5.02.
