### ISSUE TITLE
Importing from VFP does read method continued on a second line

### ISSUE THREAD

**Issue by TomGreen1943** [RickStrahl/HelpBuilderReleases#58]
(Oops: The title should read ...DOESN'T...)

I have a class method (in a .PRG) like this:

<pre>procedure MyMethod(tcArg1, tcArg2, ;
        (tcArg3, tcArg4)</pre>

Importing class does not find all the parameters. In fact it does not find any parameters.

**Comment by RickStrahl** [comment]
The parsing algorithm is pretty finicky. The syntax above is invalid anyway - the second open quote is invalid. But I believe the importer only reads the first line.

Probably needs fixing but it's low priority.

**Comment by TomGreen1943** [comment]
Thanks, Rick. You're right, my sample was not correct in my message (the extra open parenthesis), but the problem was still there.

I finally decided to write my own parser. It follows my own personal coding conventions. I don't know if anyone would be interested in it, but I would be happy to share it. It starts with a PARSEPRG.prg which returns an object with arrays of classes, methods, parameters, and properties.
