### ISSUE TITLE
Contents tree missing in final output

### ISSUE THREAD

**Issue by TomGreen1943** [RickStrahl/HelpBuilderReleases#59]
I have a feeling I'm doing something wrong. The contents tree shows in the Help Builder, but it doesn't get generated, neither in a .CHM nor a web version.

Here is the HelpBuilder view:
![image](https://cloud.githubusercontent.com/assets/3146467/21756436/55dadbaa-d5ef-11e6-92ed-de818439471a.png)

Here is the HTML view. The .CHM view is the same:
![image](https://cloud.githubusercontent.com/assets/3146467/21756444/6bd4c056-d5ef-11e6-825b-2fbb24bccfcd.png)

**Comment by RickStrahl** [comment]
Make sure your root topic is of type `INDEX` and there are not more than one `INDEX` in the table.

If the top level topic is not INDEX nothing gets generated because that's the root topic. Based on what I see in HB it looks like it is so it's probably multiple INDEX or EMPTY topics.

**Comment by TomGreen1943** [comment]
Thanks, Rick. I found the problem. Everything was effectively hanging off my root INDEX topic, and that topic was marked NOCONTENT ([x]Don't-show-as-content-topic-in-HTML-help-file). So not only that, but all subtopics disappeared.
