### ISSUE TITLE
Error with Docked Web Browser Preview

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#6]
Click the Docked Web Browser Preview button in the toolbar to turn it on, close the browser window that appears, then lick the Docked Web Browser Preview button again to turn it off. An "unknown member OIE" error appears.

**Comment by RickStrahl** [comment]
Ok, fixed that issue, plus when you close the browser window the Preview button gets unchecked assuming the intent is to close the window permanently until re-opened.
