### ISSUE TITLE
Word 2016 not recognized for PDF or Word conversion of Help File

### ISSUE THREAD

**Issue by larrymci** [RickStrahl/HelpBuilderReleases#60]
I am using version 5.0.255 of HTML Help Builder and need to convert a help project to PDF or Word.  I have Office 2016 installed but the conversion fails with the message "Sorry but you don't appear to have Word 2010 or later installed".

**Comment by RickStrahl** [comment]
Not sure. Just tried it here and it works for me. There's no reason this shouldn't work unless there's some system policy against loading EXE COM servers on your machine.

**Comment by TomGreen1943** [comment]
Thanks, Rick. I think I found it. J

 

Tom Green

Carver Technologies Inc.

514-952-0419

 <mailto:tom.green@carvertechnologies.com> tom.green@carvertechnologies.com 

 <mailto:tom.green@umana.ca> tom.green@umana.ca

 <http://www.umana.ca/> www.umana.ca

**Comment by larrymci** [comment]
I also tried running HTML Help Builder as Administrator and it still cannot find MS Word.

**Comment by RickStrahl** [comment]
Well I don't know then. 

Try instantiating Word from FoxPro and see what you get.

```
o = CREATEOBJECT("Word.Application")
o.Visible = .t.
```

**Comment by larrymci** [comment]
No luck is Foxpro either:

Class definition Word.Application not found.

 I have searched through the Windows registry and it does not exist.  I found “Word.Appllcation.16” but it is not registered as a COM object.

Larry McIntosh


> 
> 
> Telephone: 0416 161 816
> Facsimile: +61 8 9384-2227
> Visit our website at http://www.comsense.com.au <http://www.comsense.com.au/>
> Email larrymci@comsense.com.au <mailto:larrymci@comsense.com.au>
> CAUTION
> This message may contain privileged and confidential information. If you reasonably believe you were not the intended recipient of this message you are hereby notified that any use, dissemination, distribution or reproduction of this message its contents or context is prohibited. The forwarding of e-mail communications without permission from the sender is illegal.
> If you have received this message in error please notify Comsense Datasystems of Australia immediately via larrymci@comsense.com.au <mailto:larrymci@comsense.com.au> Any views expressed in this message are those of the individual sender and may not necessarily reflect the views of Comsense Datasystems of Australia. Comsense Datasystems of Australia use, and fully maintain, Network Associates McAfee Virusscan for virus protection. No guarantee is made that this communication and/or any attachment therein is free from viruses. No liability is accepted for any loss or damage, which has or may occur as a result, direct or indirect, of this communication and/or any attachments.
> P PLEASE CONSIDER THE ENVIRONMENT BEFORE YOU PRINT THIS E-MAIL!

**Comment by RickStrahl** [comment]
Well looks like your installation is borked. Reinstall or do a repair on Office. You might want to check your AV software too - that might be disabling COM access but if it's missing hte in the registry something is screwed up. This stuff has to be there for any automation to work.

**Comment by larrymci** [comment]
Thanks, Rick

I did a full repair of Office 365 and it is working now.  Thanks for the prompt response.

Larry McIntosh


> 
> 
> Telephone: 0416 161 816
> Facsimile: +61 8 9384-2227
> Visit our website at http://www.comsense.com.au <http://www.comsense.com.au/>
> Email larrymci@comsense.com.au <mailto:larrymci@comsense.com.au>
> CAUTION
> This message may contain privileged and confidential information. If you reasonably believe you were not the intended recipient of this message you are hereby notified that any use, dissemination, distribution or reproduction of this message its contents or context is prohibited. The forwarding of e-mail communications without permission from the sender is illegal.
> If you have received this message in error please notify Comsense Datasystems of Australia immediately via larrymci@comsense.com.au <mailto:larrymci@comsense.com.au> Any views expressed in this message are those of the individual sender and may not necessarily reflect the views of Comsense Datasystems of Australia. Comsense Datasystems of Australia use, and fully maintain, Network Associates McAfee Virusscan for virus protection. No guarantee is made that this communication and/or any attachment therein is free from viruses. No liability is accepted for any loss or damage, which has or may occur as a result, direct or indirect, of this communication and/or any attachments.
> P PLEASE CONSIDER THE ENVIRONMENT BEFORE YOU PRINT THIS E-MAIL!

**Comment by RickStrahl** [comment]
FWIW I'm adding new features (probably for 5.03) that will generate a PDF document differently and doesn't required Word to work.
