### ISSUE TITLE
West Wind Html Help stop to work

### ISSUE THREAD

**Issue by RogerioPicilli** [RickStrahl/HelpBuilderReleases#61]
Dear all,

I have a registered version of WWHtml Help (Version 4) and I use this version a lot. I received an email to test the new version 5. After install that version my registered version stop to work.
Actually neither is working.
How can I have my registered version back to live.

Regards

Rogerio Picilli
rogerio@docs.com.br

**Comment by RickStrahl** [comment]
If you want to use version 5.0 you need to upgrade. If you want to use version 4 you need to reinstall.

You can install both versions side by side but you have to make sure you install them into separate folders.
