### ISSUE TITLE
Help 5.0.255

### ISSUE THREAD

**Issue by JaeggiGerhard** [RickStrahl/HelpBuilderReleases#62]
Hi Rick
The "Umlaute" (äöü) does not work correctly!
Thank You

Gerhard Jaeggi

**Comment by RickStrahl** [comment]
Which part? Please post an example what doesn't work.

**Comment by JaeggiGerhard** [comment]
The part is HTML-Rendering-Engine.
In Edit-Topic-Mode write a Umlaut (ü).
In Web-View you see another character!

**Comment by RickStrahl** [comment]
That should be fixed (has been for a bit). Check again in 5.02 please.
