### ISSUE TITLE
Help Builder stopped Working

### ISSUE THREAD

**Issue by paul-gaidis** [RickStrahl/HelpBuilderReleases#63]
JUST AFTER THE SPLASH SCREEN I GET A 

"File does not Exist"
"System Error #1 "

Tried reinstalling several times...............

**Comment by RickStrahl** [comment]
Try deleting or removing:

`C:\Users\<username>l\Documents\Html Help Builder Projects\wwhelp.config`

Sounds like perhaps there's some errand setting in the configuration file. If that doesn't work I'm not sure. If you reinstall make sure you wipe the install folder completely just to be sure.

**Comment by paul-gaidis** [comment]
See below…..form the error log

Is it because I don’t have “C:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\WWHELP.VCT“




03/30/17 10:20:07 AM - Error No: 1
Line No:  36
Program:  PROCEDURE WWHELPFORM.OIMAGES.INIT C:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\WWHELP.VCT
Error Msg:File does not exist.

Call Stack:
1. c:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | C:\Program Files (x86)\West Wind Html Help Builder\wwhelpmain.prg (285) |

----
2. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.timer | c:\program files (x86)\west wind html help builder\wwhelp.vct (30) |
   thisform.DoEditOperation(lcName)
----
3. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | c:\program files (x86)\west wind html help builder\wwhelp.vct (108) |
                                THISFORM.OPEN(,.T.)
----
4. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.open | c:\program files (x86)\west wind html help builder\wwhelp.vct (92) |
   THISFORM.oImages.Init()
----
5. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.oimages.init | c:\program files (x86)\west wind html help builder\wwhelp.vct (36) |
         llResult = THIS.OBJECT.ListImages.ADD(,UPPER(TRIM(cData)),LOADPICTURE(lcImage) )
----
6. errors.fxp | ON...  | C:\Program Files (x86)\West Wind Html Help Builder\errors.prg (120) |

----


Paul Gaidis
Toll Global Forwarding
732-750-9000 x143

**Comment by RickStrahl** [comment]
That's not good. :-)

You need to reinstall and perhaps set your Anti-virus software so it won't delete files. That file should be there and there's no reason for it to go missing unless something is deleting it. AV is the most likely culprit...

**Comment by RickStrahl** [comment]
No i don't think so. The application is compiled so that file should be part of the EXE, but there is something that is not found.

It looks like it's a missing image resource - most likely icons in an active project. This is why I say, try deleting the configuration file, then restarting help builder, which should be a clean configuration with no project active. It should start Help Builder to an empty environment.

If that works then the issue is with the project and potentially some files that are missing...
