### ISSUE TITLE
Automatic save markdown editor - error 

### ISSUE THREAD

**Issue by zdenekkrejci** [RickStrahl/HelpBuilderReleases#65]
#### Error Message:
LOHTML není objekt.

#### Module: 
PROCEDURE WWHELPFORM.OHELP.RENDERTOPICTOFILE C:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\WWHELP.VCT

#### Line:
14

#### Call Stack:
1. c:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | c:\program files (x86)\west wind html help builder\wwhelpmain.prg (292) |

----
2. c:\program files (x86)\west wind html help builder\wwhelp_editor.vct | wwhelpform.oviewer.pgbody.txtbody.previewmarkdown | c:\program files (x86)\west wind html help builder\wwhelp_editor.vct (15) |
     THISFORM.DoEditOperation("cmdSave",lcAnchor)
----
3. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | c:\program files (x86)\west wind html help builder\wwhelp.vct (41) |
   			THISFORM.SaveTopic(.T.)
----
4. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.savetopic | c:\program files (x86)\west wind html help builder\wwhelp.vct (13) |
   	THISFORM.oHelp.RenderTopicToFile()
----
5. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.ohelp.rendertopictofile | c:\program files (x86)\west wind html help builder\wwhelp.vct (14) |
   loHTML.Write(  STRCONV(loHelp.RenderTopic(lcTopicId),9) )
----
6. errors.fxp | ON...  | c:\program files (x86)\west wind html help builder\errors.prg (120) |

----

#### Window:
WWHELPFORM

**Comment by RickStrahl** [comment]
Thank you but not enough info to follow this up.
