### ISSUE TITLE
System Error # 1 

### ISSUE THREAD

**Issue by MesquiteIT** [RickStrahl/HelpBuilderReleases#68]
I was trying to create a new project. Here is the error message I got.
File 'c:\program files (x86)\west wind html help builder\bmp\wwhelpicons.bmp' does not exist.
 System Error # 1 

#### Error Message:
File 'c:\program files (x86)\west wind html help builder\bmp\wwhelpicons.bmp' does not exist.

#### Module: 
PROCEDURE WWHELPFORM.OHELP.CREATEPROJECT C:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\WWHELP.VCT

#### Line:
37

#### Call Stack:
1. c:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | C:\Program Files (x86)\West Wind Html Help Builder\wwhelpmain.prg (292) |

----
2. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.timer | c:\program files (x86)\west wind html help builder\wwhelp.vct (30) |
   thisform.DoEditOperation(lcName)
----
3. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | c:\program files (x86)\west wind html help builder\wwhelp.vct (86) |
   		THISFORM.RunWizard("wizNewProject")
----
4. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.runwizard | c:\program files (x86)\west wind html help builder\wwhelp.vct (29) |
   loBuild.Show()
----
5. c:\program files (x86)\west wind html help builder\wwhelp_ui.vct | wiznewproject.cmdfinish.click | c:\program files (x86)\west wind html help builder\wwhelp_ui.vct (3) |
   THISFORM.GoFinish
----
6. c:\program files (x86)\west wind html help builder\wwhelp_ui.vct | wiznewproject.gofinish | c:\program files (x86)\west wind html help builder\wwhelp_ui.vct (2) |
   IF THISFORM.CreateProject()
----
7. c:\program files (x86)\west wind html help builder\wwhelp_ui.vct | wiznewproject.createproject | c:\program files (x86)\west wind html help builder\wwhelp_ui.vct (8) |
   llRetVal = THIS.oHelpForm.oHelp.CreateProject(lcFile,lcTitle,lcCompany)
----
8. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.ohelp.createproject | c:\program files (x86)\west wind html help builder\wwhelp.vct (37) |
   COPY FILE (this.cAppStartPath + "bmp\wwhelpicons.bmp") TO (lcPath + "bmp\" + JUSTSTEM(lcFIle) + "Icons.bmp")
----
9. errors.fxp | ON...  | C:\Program Files (x86)\West Wind Html Help Builder\errors.prg (120) |

----

#### Window:
WIZNEWPROJECT

**Comment by RickStrahl** [comment]
Thank you - Fixed in 5.05.1. Installer ended up not deploying this file for some reason. It's there now from the download page. Chocolatey should be updated shortly.

**Comment by MesquiteIT** [comment]
Thank you Rick
