### ISSUE TITLE
Minimize files for web-based help

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#69]
I'm trying to minimize what I upload to my web site because right now the Templates folder alone has 50MB in 1,500 files, which takes a while to upload! Here are some suggestions that would make this easier:

- index2.htm and indexpage.htm both use templates/wwhelp.js while all other files use that file in templates/scripts so there are two copies.
- indexpage.htm use templates/jquery.min.js while all other files use that file in templates/scripts, except index2.htm and tableofcontents.htm which use a CDN (tableofcontents.htm actually uses jquery.js not jquery.min.cs), so there are two copies.
- Using a CDN for Bootstrap, Fontawesome, HighlightJS, and jQuery would cut down on which files have to be deployed.
- The big one: creating a deployment folder during the build process which only has those files to upload would make this super-easy. It would only include the bare minimum set of files (for example, no bower files, no un-minified js files, no Ace folder, etc.).

Doug

**Comment by DougHennig** [comment]
Oops, looks like some of my comments are a little out-of-date. I updated templates and see there is no more index2.htm and indexpage.htm.

I also tried the Zip Files for Web function in the Help Compiler Results dialog and while it basically does what I asked for in my "creating a deployment folder" idea, it's missing most of the files needed in the templates folder.

**Comment by RickStrahl** [comment]
You can strip out all the template theme subfolders from your project - the only one really used is the root, the other ones are there just for switching, so they are not used once the help file is built/deployed.

However, if you use the FTP upload it should be able to upload only files that have changed.
