### ISSUE TITLE
Variable 'PLUSEPRAGMALINES' is not found.

### ISSUE THREAD

**Issue by marceldesmet** [RickStrahl/HelpBuilderReleases#71]
#### Error Message:
Variable 'PLUSEPRAGMALINES' is not found.

#### Module: 
PROCEDURE WWHELPFORM.OHELP.FORMATHTML C:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\WWHELP.VCT

#### Line:
24

#### Call Stack:
1. c:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | C:\Program Files (x86)\West Wind Html Help Builder\wwhelpmain.prg (292) |

----
2. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.timer | c:\program files (x86)\west wind html help builder\wwhelp.vct (30) |
   thisform.DoEditOperation(lcName)
----
3. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | c:\program files (x86)\west wind html help builder\wwhelp.vct (648) |
   		loEditBox.SELTEXT = THISFORM.oHelp.FormatHTML(_CLIPTEXT,.T.)
----
4. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.ohelp.formathtml | c:\program files (x86)\west wind html help builder\wwhelp.vct (24) |
         poMarkdownParser.CreateParser(.t.,plUsePragmaLines)
----
5. errors.fxp | ON...  | C:\Program Files (x86)\West Wind Html Help Builder\errors.prg (120) |

----

#### Window:
WWHELPFORM

**Comment by RickStrahl** [comment]
Thanks. Fixed.
