### ISSUE TITLE
OLE IDispatch exception code 0 from TLI

### ISSUE THREAD

**Issue by MesquiteIT** [RickStrahl/HelpBuilderReleases#72]
#### Error Message:
OLE IDispatch exception code 0 from TLI: The specified file could not be found, or the file doesn't contain a valid typelib...

#### Module: 
PROCEDURE WWTYPELIB.OPEN C:\PROGRAM FILES (X86)\COMMON\WWTYPELIB.VCT

#### Line:
15

#### Call Stack:
1. c:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | C:\Program Files (x86)\West Wind Html Help Builder\wwhelpmain.prg (292) |

----
2. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.timer | c:\program files (x86)\west wind html help builder\wwhelp.vct (30) |
   thisform.DoEditOperation(lcName)
----
3. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | c:\program files (x86)\west wind html help builder\wwhelp.vct (322) |
   		THISFORM.RunWizard("wizImportVCX")
----
4. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.runwizard | c:\program files (x86)\west wind html help builder\wwhelp.vct (29) |
   loBuild.Show()
----
5. c:\program files (x86)\west wind html help builder\wwhelp_ui.vct | wizimportvcx.cmdfinish.click | c:\program files (x86)\west wind html help builder\wwhelp_ui.vct (3) |
   THISFORM.GoFinish
----
6. c:\program files (x86)\west wind html help builder\wwhelp_ui.vct | wizimportvcx.gofinish | c:\program files (x86)\west wind html help builder\wwhelp_ui.vct (34) |
      llRet = loImport.ImportTypeLibClasses(THISFORM.oHelpForm.oHelp)
----
7. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpimportvcx.importtypelibclasses | c:\program files (x86)\west wind html help builder\wwhelp.vct (24) |
   IF !loTLB.Open(lcTypeLib)
----
8. c:\program files (x86)\common\wwtypelib.vct | wwtypelib.open | c:\program files (x86)\common\wwtypelib.vct (15) |
   THIS.oTypeInfo = THIS.oTypeLib.TypeLibInfoFromFile(lcTypeLib)
----
9. errors.fxp | ON...  | C:\Program Files (x86)\West Wind Html Help Builder\errors.prg (120) |

----

#### Window:
WWPROGRESSFORM

**Comment by RickStrahl** [comment]
Thanks. Needs some additional exception capture, but the error is because the file is not or does not contain a type library...
