### ISSUE TITLE
Error generating HTML files

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#73]
#### Error Message:
LOHTML is not an object.

#### Module: 
PROCEDURE WWHELPFORM.OHELP.GENERATEHTML D:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\WWHELP.VCT

#### Line:
38

#### Call Stack:
1. d:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | d:\program files (x86)\west wind html help builder\wwhelpmain.prg (292) |

----
2. d:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.timer | d:\program files (x86)\west wind html help builder\wwhelp.vct (30) |
   thisform.DoEditOperation(lcName)
----
3. d:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | d:\program files (x86)\west wind html help builder\wwhelp.vct (346) |
   		THISFORM.RunWizard("wizBuildOutput")
----
4. d:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.runwizard | d:\program files (x86)\west wind html help builder\wwhelp.vct (29) |
   loBuild.Show()
----
5. d:\program files (x86)\west wind html help builder\wwhelp_ui.vct | wizbuildoutput.cmdfinish.click | d:\program files (x86)\west wind html help builder\wwhelp_ui.vct (3) |
   THISFORM.GoFinish
----
6. d:\program files (x86)\west wind html help builder\wwhelp_ui.vct | wizbuildoutput.gofinish | d:\program files (x86)\west wind html help builder\wwhelp_ui.vct (1) |
   IF THISFORM.GenerateOutput()
----
7. d:\program files (x86)\west wind html help builder\wwhelp_ui.vct | wizbuildoutput.generateoutput | d:\program files (x86)\west wind html help builder\wwhelp_ui.vct (41) |
      loHelp.GenerateHTML()
----
8. d:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.ohelp.generatehtml | d:\program files (x86)\west wind html help builder\wwhelp.vct (38) |
      loHTML.Write(  STRCONV(THIS.RenderTopic(),9) )
----
9. errors.fxp | ON...  | d:\program files (x86)\west wind html help builder\errors.prg (120) |

----

#### Window:
WWPROGRESSFORM

**Comment by RickStrahl** [comment]
Is it repeatable or a one off?

I've rendering very large files (Web Connection docs) with no issues...

**Comment by DougHennig** [comment]
[HTMLHelp.zip](https://github.com/RickStrahl/HelpBuilderReleases/files/1925920/HTMLHelp.zip)

It happens a lot. Attached is the project the error occurred on. I customized a few templates but other than that it should be a straightforward project:

* _Layout.wcs: removed West Wind logo in header and footer, updated "small" section in footer, and removed nav class="topic-outline" section
* _LayoutIndex.wcs: new file: copy of _layout.wcs but the byline section is removed and has different title (used by Index.wcs)
* Header.wcs: removed header class="content-title" section
* Index.wcs: use _LayoutIndex.wcs instead of _Layout.wcs
* TableOfContents.wcs: removed HOME LINK
* Topic.wcs: removed h1 class="content-title" section
* wwHelp.css: changed font size for byline to 1.4em plus path for vsizegrip.png to bmp

**Comment by RickStrahl** [comment]
Thanks for the project - that should help narrow it down. I'll take a look later.

**Comment by RickStrahl** [comment]
Ok, so I took a quick look. I'm able to generate the output for the project with no problems:

![image](https://user-images.githubusercontent.com/1374013/38963915-f4118f60-430f-11e8-8130-137ea4e26693.png)

Made no changes - just unzipped and opened the hbp from the copied location.

When you say it happens a lot, does that mean sometimes it works sometimes it doesn't? If that's the case I suspect the issue might be related to the UI.

CSS and template changes shouldn't cause a problem with the output generation. It's RenderTopic() that's failing so there's something happening that's causing the generation to fail.

It looks like the error is here:

```foxpro
   loHTML = CREATEOBJECT([WWC_RESPONSEFILE],lcFileName)
   THIS.SetTemplate()
   
   *** Format to UTF8
   loHTML.Write(  STRCONV(THIS.RenderTopic(),9) )
   loHTML = .F.
```

so I'm guessing there is either a problem with a file being not accessible/writable somehow although I'm not sure why that should be - or possibly lcFilename is pointing somewhere invalid giving an invalid filename. Reviewing that code I did find a few non-local-declared variables and it's possible under some odd circumstances that that might end up pointing at the wrong file.

I'm going to rebuild with these changes and upload a new version.

**Comment by DougHennig** [comment]
Yeah, it's intermittent. Sometimes I get it when the web view window is refreshed, and I often get it when building HTML, but it seems to stop at different places rather than consistently on the same topic. I just tried it again with that project and it worked three times in a row, yet yesterday I couldn't build successfully even once. Intermittent issues are a bitch!
