### ISSUE TITLE
Building CHM fails when space in file path

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#75]
If the HBP file is in a folder with a space in the name, the CHM file won't build. I confirmed this by removing the space from the folder name and trying again.

**Comment by RickStrahl** [comment]
I don't see that. I have both project files and folders with spaces and the files build fine.

Here's an example:

![image](https://user-images.githubusercontent.com/1374013/39216555-eae43e36-47b7-11e8-8886-da543155d742.png)

This project lives in:

```
%homepath%\documents\West Wind WebSurge\West Wind WebSurge.hbp
```

There must be something else happening...

**Comment by DougHennig** [comment]
OK, this is weird. I created a new project in a folder named Test Folder on my desktop and building the CHM works. However, when I build a project named SFQuery.hbp in D:\Development\SFQueryProjects\Stonefield Query for Legrand CRM\Data\HTMLHelp, I get:

The Help file was not built
---

Usage:   hhc <filename>
    where <filename> = an HTML Help project file
Example: hhc myfile.hhp

If I close the project, remove the spaces from "Stonefield Query for Legrand CRM", reopen the project, and build, it works.
