### ISSUE TITLE
Issue with External Link

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#79]
Yes, this is a user issue but it took me an hour to track down, so perhaps the UI could prevent it in the future.

I had an issue where the CHM wouldn't build. If I opened the HHP file in HTML Help Workshop directly, it would open for a moment and then just close by itself. I finally tracked the problem down to an issue with the HHC file: for one of the topics, the value element of the param name="Local" element had the body of the topic instead of the name of the HTM file. When I looked at that topic in wwHB, I found I had somehow turned on the External Link setting.

So, my suggestion is to give a warning when rendering if External Link is turned on but the content isn't just a URL.

**Comment by RickStrahl** [comment]
I ran into this recently myself and I think that’s been fixed.
