### ISSUE TITLE
Markdown conversion issues

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#8]
I realize conversion won't be perfect but here are some issues JIC you can handle them:
- I had some text like this:

&lt;&lt;li&gt;&gt;Some text

Notice there's no space between &lt;&lt;li&gt;&gt; and "Some text". When converted to Markdown, it becomes:

*Some text

Since there's no space after the *, Markdown doesn't treat it as a bullet. So, when converting &lt;&lt;li&gt;&gt;, add a space after the \* if there isn't one already.
- I have some topics that have a list within a list i.e.:

&lt;&lt;ul&gt;&gt;
&lt;&lt;li&gt;&gt;Bullet 1
&lt;&lt;ul&gt;&gt;
&lt;&lt;li&gt;&gt;Subbullet 2
&lt;&lt;/ul&gt;&gt;
&lt;&lt;li&gt;&gt;Bullet 2

In that case, the \* for the subbullets needs to be prefixed with a tab.

**Comment by RickStrahl** [comment]
Yeah that's not going to happen :-) The reverse parser is pretty simple and basically hunts for specific double HTML tags and then replaces them with equivalent markdown. This is meant to be a helper not a perfect conversion tool and it's a temporary feature in Help Builder.

**Comment by RickStrahl** [comment]
FWIW, I've been processing topics as I edit them. I'm not updating everything right away - only when I actually edit a topic, so the process is sporadic one at a time for me. I convert then preview to see what issues there are. Most topics come out just fine, but some require a handful of small adjustments like your list formatting. It's usually pretty easy to see in the preview and easy to fix in the editor, but yes it does require some manual review.
