### ISSUE TITLE
Help File not built

### ISSUE THREAD

**Issue by johnniekipper** [RickStrahl/HelpBuilderReleases#80]
When I try to create help I get the message "Help File not built"

Only information it shows is ;

The Help file was not built
---
Error compiling the Help Project. The CHM help file was not built.

Happening with a very small project.

**Comment by RickStrahl** [comment]
did you install the help compiler?

https://docs.microsoft.com/en-us/previous-versions/windows/desktop/htmlhelp/microsoft-html-help-downloads

Make sure HTML Help Workshop is installed.

If you have it installed and there are errors, open the project in Html Help Workshop and compile from there - sometimes that works when the command line compiler does not and it gives more error information usually.
