### ISSUE TITLE
Issue with menu items

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#81]
A couple of functions in the Help menu aren't working:

* Check for Help Builder Updates gives a "There's been an error retrieving the version info."

* Help Builder Support navigates to https://support.west-wind.com/default.asp?Forum=HTML+Help+Builder&Forum=HTML+Help+Builder, which gives a 404.

This is version 5.10.0.

**Comment by RickStrahl** [comment]
Thanks. Both of these are fixed.

Caused by the recent server migration and broken links on the server. Will be updated in the next release.
