### ISSUE TITLE
FontAwesome icons in CHM?

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#82]
Is there a way to get FontAwesome icons, such as @icon-info-circle, to appear in a CHM file? They do appear properly in the HTML uploaded to a web site but display as blank in a CHM.

**Comment by RickStrahl** [comment]
I don't think there is a way to make that work. I'm not quite sure why it doesn't work. My guess is its related to the fact that the CHM doesn't allow the font mime-type/extension or doesn't know how to interpret the font and is not allowing it via the security blocking that's active in CHM files. Checked the page in IE with F12 tools and while it's not rendering it's also not showing any errors in the console so not sure why that's not working.

Maybe it's time to move help links to point to the Web site... 

+++ Rick ---

**Comment by DougHennig** [comment]
I figured as much. Just thought I'd check.
