### ISSUE TITLE
Error in Export Html Output to Zip File

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#85]
#### Error Message:
OLE IDispatch exception code 0 from wwDotNetBridge: Method 'Westwind.WebConnection.FileUtils.SaveFileDialog' not found...

#### Module: 
PROCEDURE WWDOTNETBRIDGE.INVOKESTATICMETHOD WWDOTNETBRIDGE.FXP

#### Line:
644

#### Call Stack:
1. d:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | d:\program files (x86)\west wind html help builder\wwhelpmain.prg (306) |

----
2. d:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.timer | d:\program files (x86)\west wind html help builder\wwhelp.vct (30) |
   thisform.DoEditOperation(lcName)
----
3. d:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | d:\program files (x86)\west wind html help builder\wwhelp.vct (230) |
   		lcZipFileName = SaveFileDialog(JUSTPATH(THIS.oHelp.cFileName) + "\" + LOWER(JUSTSTEM(THIS.oHelp.cFileName)) + 				"_HTML_"  +  CHRTRAN(DTOC(DATE()),"/\","-") + ".zip","zip",          		"Zip Files|*.zip",.F.)
----
4. wwutils.fxp | savefiledialog | d:\webconnection\fox\classes\wwutils.prg (2934) |

----
5. wwdotnetbridge.fxp | wwdotnetbridge.invokestaticmethod | d:\webconnection\fox\classes\wwdotnetbridge.prg (644) |

----
6. errors.fxp | ON...  | d:\program files (x86)\west wind html help builder\errors.prg (120) |

----

#### Window:
FRMWEBBROWSER

**Comment by RickStrahl** [comment]
It turns out there's a weird problem with references pointing at the wrong dll. 

I'm going through and cleaning up the distribution files to get things into the right place, but it's turning out to be a bit more complicated than expected :-)

**Comment by RickStrahl** [comment]
Fixed in 5.16.3.
