### ISSUE TITLE
config for MarkdigExtensions

### ISSUE THREAD

**Issue by sphynx79** [RickStrahl/HelpBuilderReleases#87]
I see that in Markdown Monster i can add in config 
"MarkdigExtensions": "attributes"
to set css attribute inline in markdown.

How i can set this in West Wind Html Help.

Thanks

**Comment by RickStrahl** [comment]
It's not supported at the moment.

**Comment by RickStrahl** [comment]
I've added support for this now via the `<markdigextensions>` configuration key:

https://helpbuilder.west-wind.com/docs/_5gm0urpr3.htm

The entire pipeline (with exception of pragmalines and nohtml) is now controlled by this configuration and you can override it. Note you'll have to provide all keys not just the additions.

I've also added attributes into the default string so your default request probably doesn't need a custom config at this point.
