### ISSUE TITLE
System Error #1

### ISSUE THREAD

**Issue by rschummer** [RickStrahl/HelpBuilderReleases#89]
I updated templates and still get this error when starting Help Builder. It is happening for only one of the four projects, but I cannot tell what file is missing. 

I did not realize v5.17.0 was released too, so I installed and this is still an issue.

#### Error Message:
File does not exist.
DO "c:\program files (x86)\west wind html help builder\wwhelp.exe" 

#### Module: 
PROCEDURE WWHELPFORM.OIMAGES.INIT C:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\WWHELP.VCT

#### Line:
38

#### Call Stack:
1. c:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | C:\Program Files (x86)\West Wind Html Help Builder\wwhelpmain.prg (280) |

----
2. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.init | c:\program files (x86)\west wind html help builder\wwhelp.vct (93) |
   IF !THIS.Open(,,.T.)  && Silent Operation
----
3. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.open | c:\program files (x86)\west wind html help builder\wwhelp.vct (92) |
   THISFORM.oImages.Init()
----
4. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.oimages.init | c:\program files (x86)\west wind html help builder\wwhelp.vct (38) |
         llResult = THIS.OBJECT.ListImages.ADD(,UPPER(TRIM(cData)),LOADPICTURE(lcImage) )
----
5. errors.fxp | ON...  | C:\Program Files (x86)\West Wind Html Help Builder\errors.prg (120) |

----

#### Window:
FORM1

**Comment by RickStrahl** [comment]
Hmmm... this looks like missing images in the `BMP` folder of the project. I know this is a late response but if still a problem try copying the bmp folder from a working project into the failing project's folder.

Missing images are not supposed to hard fail, but default to a generic image, so I am a bit puzzled by why this would crash HB.
