### ISSUE TITLE
Last Topic list not updated properly

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#9]
This isn't new in 5.0 and has bugged me for a while so I finally figured out the issue.

Steps to reproduce:
- Open a project
- Click on a few topics in the TreeView
- Click the down arrow for the Last Topic button: notice topics are listed in the reverse order selected as expected
- Select a topic that has a link to another topic. Click the link to go to the other topic.
- Click the Last Topic button.

Observed:

Sometimes you go back to the previous topic, sometimes nothing happens, sometimes you go to a previous topic but not the one in which you clicked the link. The reason is because while clicking a link moves you to another topic, it doesn't update the Last Topic list (you can see that by clicking the down arrow for that button).

**Comment by RickStrahl** [comment]
Sorry I don't follow. I see the topic being added to the last topic list. When does it not get added?

**Comment by DougHennig** [comment]
I have this set of topics:

![topics](https://cloud.githubusercontent.com/assets/12052409/9308587/9cee06aa-44ca-11e5-8e76-b958979bd94b.png)

Topic 1-1 links to Topic 2. After I open the project, I select Topic 1-1. I click the link in 1-1 to go to Topic 2. As you can see, Topic 2 is selected but doesn't appear in the topics list:

![selected](https://cloud.githubusercontent.com/assets/12052409/9308645/e6dd5342-44ca-11e5-8e38-6e2ec239baa8.png)

I select Topic 3, then click the Last Topic button and it takes me to 1-1, not 2.

**Comment by RickStrahl** [comment]
Thanks Doug! Found the problem - elusive. Only in certain situations it doesn't work when the topic is embedded a certain way. Now the topic ID is properly used after the topic is actually loaded so it should always go into the topic list. 

Fixed for post 5.0.61 releases

Now to figure out why the dynamic icons in those menus all are on black non-transparent backgrounds on Win10.

**Comment by RickStrahl** [comment]
The new build is up now and it should have this fixed. It also fixes the black icon backgrounds (not quite sure what actually changed). 

Related: The preview window (the attached window) now follows topic links and navigates the main window. It mostly behaves the same as the internal preview window which should make it easier to navigate around while you have the editor active.

Latest release is 5.0.63

**Comment by DougHennig** [comment]
Yes, this is working correctly now.
