### ISSUE TITLE
Ctrl+V does not paste

### ISSUE THREAD

**Issue by rschummer** [RickStrahl/HelpBuilderReleases#90]
Working in the editor and using keyboard Ctrl+V opens up a Save As dialog for image.png instead of pasting. Only work around is right-click and picking Paste.

v5.16.5 and v5.17.0

**Comment by RickStrahl** [comment]
Yes I've seen this as well, but it's very inconsistent. Haven't been able to pin this down when it occurs.

**Comment by RickStrahl** [comment]
There have been some tweaks in relation to this. This is a problem related to the Web Browser control and that hosts the editor and COM, which in some cases causes some sort of lock on the clipboard.  I've added some additional checks that should help retry the clipboard operations if they fail with a small delay which should make this more reliable.

FWIW, I've been noticing in Windows in general that the clipboard often times doesn't pick up Ctrl-C copied content. Using the context menu keys tends to work reliably where the short cut keys don't. Observed in VS Code, Word and a few other apps.

**Comment by RickStrahl** [comment]
Release 5.25 provides an alternate mechanism for pasted content that works around some of the UI bugs related to Clipboard access from within the Web browser. In 5.25 the JavaScript code checks for text content and if it finds text uses the default in-browser paste operations to paste text which is much more reliable and also considerably quicker - no lag as there was before.

This should be fixed now but please report if you continue to see odd paste behavior.
