### ISSUE TITLE
Script errors w/ new install

### ISSUE THREAD

**Issue by ronankeane** [RickStrahl/HelpBuilderReleases#92]
New install on Windows 7.

First, wwhelp.js - syntax error on line 536, char. 13.

Then, error - 'helpbuilder is undefined.

#### Error Message:
Unhandled Structured Exception.
ErrorNo: 1426
Message: OLE error code 0x800700aa: The requested resource is in use.
UserValue:
Details: 800700aa: The requested resource is in use
Procedure: navigate
LineNo: 7

#### Module: 
PROCEDURE FRMWEBBROWSER.NAVIGATE C:\PROGRAM FILES\WEST WIND HTML HELP BUILDER\WEBBROWSERFORM.SCT
#### Line:
9
#### Call Stack:
1. c:\program files\west wind html help builder\wwhelp.exe | wwhelpmain | C:\Program Files\West Wind Html Help Builder\wwhelpmain.prg (307) |

----
2. c:\program files\west wind html help builder\wwhelp.vct | wwhelpform.otree.nodeclick | c:\program files\west wind html help builder\wwhelp.vct (10) |
   THISFORM.GoTopic(lcPK)
----
3. c:\program files\west wind html help builder\wwhelp.vct | wwhelpform.gotopic | c:\program files\west wind html help builder\wwhelp.vct (102) |
      THIS.Preview(1,lcAnchor)
----
4. c:\program files\west wind html help builder\wwhelp.vct | wwhelpform.preview | c:\program files\west wind html help builder\wwhelp.vct (94) |
           loIE.Navigate(lcUrl)
----
5. c:\program files\west wind html help builder\webbrowserform.sct | frmwebbrowser.navigate | c:\program files\west wind html help builder\webbrowserform.sct (9) |
   ENDTRY
----
6. errors.fxp | ON...  | C:\Program Files\West Wind Html Help Builder\errors.prg (120) |

----

#### Window:
WWHELPFORM

Thanks.

**Comment by RickStrahl** [comment]
Couple of things:

* Make sure you update to the latest templates (backup first)
* Make sure that you have IE 11 installed

If you don't have IE 11 installed it can be installed from here:
https://www.microsoft.com/en-us/download/internet-explorer-11-for-windows-7-details.aspx
