### ISSUE TITLE
AnimationControl not found when searching

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#93]
#### Error Message:
Class definition ANIMATIONCONTROL is not found.

#### Module: 
PROCEDURE WWPROGRESSFORM.LOADANIMATION D:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\WWDIALOGS.VCT

#### Line:
17

#### Call Stack:
1. d:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | d:\program files (x86)\west wind html help builder\wwhelpmain.prg (307) |

----
2. d:\program files (x86)\west wind html help builder\search.sct | frmsearchtopics.cmdsearch.click | d:\program files (x86)\west wind html help builder\search.sct (6) |
   oMessage.LoadAnimation("bmp\search.avi")
----
3. d:\program files (x86)\west wind html help builder\wwdialogs.vct | wwprogressform.loadanimation | d:\program files (x86)\west wind html help builder\wwdialogs.vct (17) |
          THISFORM.AddObject("oAnimation","AnimationControl")
----
4. errors.fxp | ON...  | d:\program files (x86)\west wind html help builder\errors.prg (120) |

----

#### Window:
FRMSEARCHTOPICS

**Comment by kentraub** [comment]
I'm having the same issue with 5.20.  Is there a fix for this?

**Comment by RickStrahl** [comment]
It's a bug, but haven't gotten to it yet. Will take a look.

**Comment by RickStrahl** [comment]
Updated to 5.21 that has this issue taken care of.

Regression bug - removed a set of support ActiveX controls and this was one I didn't realize I was using (for progress). Replaced with animated Gif instead.
