### ISSUE TITLE
Copy to Folder not copying HTM files

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#95]
After building a project, using the Copy to Folder function in the Help Compiler Results dialog creates the folder structure and copies BMPs, Images, and Templates, but doesn't copy the generate HTM files. Outputting to ZIP does create a ZIP file containing all the files.

**Comment by DougHennig** [comment]
I just tried it again with a different project and this time the HTM files were copied. I tried it several times with the first project and every time it failed to copy the HTM files. Weird!

**Comment by RickStrahl** [comment]
Is this repeatable for the project that doesn't work? I wonder if there's something in that project that generates a bad file or folder name that's causing the problem? Folder name with spaces perhaps vs. no spaces? Long files names?

**Comment by DougHennig** [comment]
I can't reproduce this now, either.

**Comment by RickStrahl** [comment]
Ok, reopen if it happens again and if perhaps there's more information. Thanks Doug.
