### ISSUE TITLE
Generate Word | PDF fails to generate TOC

### ISSUE THREAD

**Issue by foxdancer** [RickStrahl/HelpBuilderReleases#96]
Create a new project and add just one INDEX entry and one sub TOPIC.
The process fails with the VBA error message below (= "Requested Member of the Collection Does Not Exist") . 
Both outputs don't have a TOC after finishing the process.

My environment:  WIN 10 + Word 2013 both **german**

![image](https://user-images.githubusercontent.com/6490302/68036371-d55e6180-fcc5-11e9-82a1-31b80b628da3.png)

**Comment by RickStrahl** [comment]
Just circling back to this:

I can't duplicate this error. 

![image](https://user-images.githubusercontent.com/1374013/81470828-af3fdf80-9188-11ea-9d6c-0915a6284a81.png)

It looks pretty bad but it works. 

Does the export work with other projects?
