### ISSUE TITLE
Selecting Addins Manager from menu crashes WWHB

### ISSUE THREAD

**Issue by rikaye** [RickStrahl/HelpBuilderReleases#99]
#### Error Message:
Unknown member OADDINS.

#### Module: 
PROCEDURE FRMADDINMANAGER.SHOWADDINLIST C:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\ADDINMANAGER.SCT

#### Line:
6

#### Call Stack:
1. c:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | C:\Program Files (x86)\West Wind Html Help Builder\wwhelpmain.prg (307) |

----
2. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.timer | c:\program files (x86)\west wind html help builder\wwhelp.vct (30) |
   thisform.DoEditOperation(lcName)
----
3. c:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | c:\program files (x86)\west wind html help builder\wwhelp.vct (512) |
   		DO FORM AddinManager
----
4. c:\program files (x86)\west wind html help builder\addinmanager.sct | frmaddinmanager.init | c:\program files (x86)\west wind html help builder\addinmanager.sct (4) |
   this.ShowAddinList()
----
5. c:\program files (x86)\west wind html help builder\addinmanager.sct | frmaddinmanager.showaddinlist | c:\program files (x86)\west wind html help builder\addinmanager.sct (6) |
   FOR EACH loAddin IN goHelp.oAddins.oAddins
----
6. errors.fxp | ON...  | C:\Program Files (x86)\West Wind Html Help Builder\errors.prg (120) |

----

#### Window:
WWHELPFORM

**Comment by RickStrahl** [comment]
Fixed some time ago.
